export const TOLIMA_CITIES = [
  "Alpujarra",
  "Alvarado",
  "Ambalema",
  "Anzoategui",
  "Armero",
  "Ataco",
  "Cajamarca",
  "Carmen de Apicala",
  "Casabianca",
  "Chaparral",
  "Coello",
  "Coyaima",
  "Cunday",
  "Dolores",
  "Espinal",
  "Falan",
  "Flandes",
  "Fresno",
  "Guamo",
  "Herveo",
  "Honda",
  "Ibague",
  "Icononzo",
  "Lerida",
  "Libano",
  "Mariquita",
  "Melgar",
  "Murillo",
  "Natagaima",
  "Ortega",
  "Palocabildo",
  "Piedras",
  "Planadas",
  "Prado",
  "Purificacion",
  "Rioblanco",
  "Roncesvalles",
  "Rovira",
  "Saldana",
  "San Antonio",
  "San Luis",
  "Santa Isabel",
  "Sucre",
  "Suarez",
  "Valle de San Juan",
  "Venadillo",
  "Villahermosa",
  "Villarrica",
];

export const EDUCATION_LEVELS = [
  { value: "primaria", label: "Primaria" },
  { value: "bachillerato", label: "Bachillerato" },
  { value: "profesional", label: "Profesional" },
  { value: "postgrado", label: "Postgrado" },
];
